# Importing  libraries
import os
import shlex
import argparse
from tqdm import tqdm

# for python3: read in python2 pickled files
import _pickle as cPickle

import gzip
from sklearn.cluster import MiniBatchKMeans
from sklearn.svm import LinearSVC
from sklearn.linear_model import Ridge
from sklearn.preprocessing import normalize
import numpy as np
import cv2
# from parmap import parmap
from sklearn.decomposition import PCA


# setting Directory

BASE_DIR = '/proj/ciptmp/sivichri/icdar17_local_features'  # Base directory
TRAIN_DIR = os.path.join(BASE_DIR, 'train') # Training directory
TEST_DIR = os.path.join(BASE_DIR, 'test') # Testing directory
TRAIN_LABELS_FILE = os.path.join(BASE_DIR, 'icdar17_labels_train.txt') # Training labels file
TEST_LABELS_FILE = os.path.join(BASE_DIR, 'icdar17_labels_test.txt') # Testing labels file

 
                                # **************************************************************

                                #                        Codebook generation

                                #***************************************************************

def parseArgs(parser):
    parser.add_argument('--labels_test', default=TEST_LABELS_FILE,      # Default testing labels file
                        help='contains test images/descriptors to load + labels')
    parser.add_argument('--labels_train', default=TRAIN_LABELS_FILE,    # Default training labels file
                        help='contains training images/descriptors to load + labels')
    # parser.add_argument('-s', '--suffix',
    #                     default='_SIFT_patch_pr.pkl.gz',        # Default suffix for image files
    #                     help='only chose those images with a specific suffix')
    parser.add_argument('--suffix_train', default='_SIFT_patch_pr.pkl.gz',
                    help='suffix for training files (e.g., .png)')
    parser.add_argument('--suffix_test', default='_SIFT_patch_pr.pkl.gz',
                    help='suffix for test files (e.g., .jpg)')
    parser.add_argument('--in_test',default=TEST_DIR,           # Default testing directory
                        help='the input folder of the test images / features')
    parser.add_argument('--in_train',  default=TRAIN_DIR,           # Default training directory
                        help='the input folder of the training images / features')
    parser.add_argument('--overwrite', action='store_true',
                        help='do not load pre-computed encodings')  # Overwrite pre-computed encodings
    parser.add_argument('--powernorm', action='store_true',     # Apply power normalization
                        help='use powernorm')
    parser.add_argument('--gmp', action='store_true',
                        help='use generalized max pooling')     # Use generalized max pooling
    parser.add_argument('--gamma', default=1, type=float,
                        help='regularization parameter of GMP')     # Regularization parameter for GMP
    parser.add_argument('--C', default=1000, type=float, 
                        help='C parameter of the SVM')      ## SVM C parameter

    parser.add_argument('--multivlad', action='store_true',
                    help='use 5 codebooks and concatenate 5 VLADs')
    parser.add_argument('--n_codebooks', default=5, type=int,
                        help='number of codebooks for multi-VLAD (default 5)')
    parser.add_argument('--n_clusters', default=100, type=int,
                        help='number of clusters per codebook (try 32 to speed up)')
    parser.add_argument('--pca_dim', default=1000, type=int,
                        help='PCA output dimensionality (<= #train=1182)')
    parser.add_argument('--pca_subset', default=0, type=int,
                        help='optional: fit PCA on random subset of train (0=use all)')
    return parser

def getFiles(folder, pattern, labelfile):
    """ 
    returns files and associated labels by reading the labelfile 
    parameters:
        folder: inputfolder
        pattern: new suffix
        labelfiles: contains a list of filename and labels
    return: absolute filenames + labels 
    """

    """
  This function reads a labelfile containing file names and their associated class IDs, processes the filenames, 
  and returns a list of full file paths along with their respective labels. First, the labelfile is opened and its lines 
  are read. For each line, the filename and class ID are extracted by splitting the line. The function then iterates through 
  a predefined set of file extensions (.pkl.gz, .txt, .png, etc.) and removes any matching extension from the filename. 
  After that, a new filename is created by appending a specified suffix (pattern) to the filename, and the full file path 
  is generated by combining the given folder path and the new filename. The function then appends this full path to a list 
  of files and the class ID to a list of labels. Finally, the function returns these two lists: one containing the full 
  paths of the files and the other containing the corresponding class IDs.
    """


    # read labelfile
    with open(labelfile, 'r') as f: # Open the labelfile
        all_lines = f.readlines()   # Read all lines
    
    # get filenames from labelfile
    all_files = []  # Initialize list for all files
    labels = []     # Initialize list for all labels
    for line in all_lines:      # Iterate over all lines
        # using shlex we also allow spaces in filenames when escaped w. ""
        splits = shlex.split(line)  # Split the line
        file_name = splits[0]       # Get the filename
        class_id = splits[1]        # Get the class ID

        # strip all known endings, note: os.path.splitext() doesnt work for
        # '.' in the filenames, so let's do it this way...
        for p in ['.pkl.gz', '.txt', '.png', '.jpg', '.tif', '.ocvmb','.csv']:  # Iterate over all file extensions
            if file_name.endswith(p):
                file_name = file_name.replace(p,'') # Replace the file extension

        # get now new file name
        true_file_name = os.path.join(folder, file_name + pattern)      # Get the full path
        all_files.append(true_file_name)        # Append the full path to the list of all files
        labels.append(class_id)         # Append the class ID to the list of labels

    return all_files, labels # Return the list of all files and labels

def loadRandomDescriptors(files, max_descriptors):
    """ 
    load roughly `max_descriptors` random descriptors
    parameters:
        files: list of filenames containing local features of dimension D
        max_descriptors: maximum number of descriptors (Q)
    returns: QxD matrix of descriptors
    """

    """
    The loadRandomDescriptors function loads a specified number of random descriptors from a list of files. It selects up to 100 files randomly
      and calculates how many descriptors to load from each file. For each file, it loads the descriptors, randomly selects a subset, and appends
        them to a list. After processing all files, the function concatenates the descriptors into a single matrix and returns it. This matrix 
        contains max_descriptors descriptors with a specific dimension, D.
    """



    # let's just take 100 files to speed-up the process
    # max_files = 100     # maximum number of files to load
    # indices = np.random.permutation(max_files)  # shuffle the files
    max_files = min(100, len(files))
    indices = np.random.permutation(len(files))[:max_files]
    files = np.array(files)[indices]        # select a subset of files
   
    # rough number of descriptors per file that we have to load
    max_descs_per_file = int(max_descriptors / len(files))          # maximum number of descriptors per file

    descriptors = []        # initialize list of descriptors
    # for i in tqdm(range(len(files))):       # iterate over all files
    #     with gzip.open(files[i], 'rb') as ff:       # open the file
    #         # for python2
    #         # desc = cPickle.load(ff)
    #         # for python3
    #         desc = cPickle.load(ff, encoding='latin1')      # load the descriptors
            
    #     # get some random ones
    #     indices = np.random.choice(len(desc),               # select a subset of descriptors
    #                                min(len(desc),                   
    #                                    int(max_descs_per_file)),
    #                                replace=False)
    #     desc = desc[ indices ]          # select the descriptors
    #     descriptors.append(desc)            # append the descriptors
    for i in tqdm(range(len(files))):

        # NEW: load either .pkl.gz descriptors OR compute from image
        desc = loadDescsFromFile(files[i])
        desc = np.asarray(desc, dtype=np.float32)

        # skip files with no descriptors
        if desc.ndim != 2 or desc.shape[0] == 0:
            continue

        # get some random ones
        idx = np.random.choice(desc.shape[0],
                            min(desc.shape[0], int(max_descs_per_file)),
                            replace=False)
        descriptors.append(desc[idx])

    
    descriptors = np.concatenate(descriptors, axis=0)       # concatenate the descriptors
    return descriptors          # return the descriptors

def dictionary(descriptors, n_clusters):
    """ 
    return cluster centers for the descriptors 
    parameters:
        descriptors: NxD matrix of local descriptors
        n_clusters: number of clusters = K
    returns: KxD matrix of K clusters
    """
    """
    The dictionary function performs clustering on a set of local descriptors to return cluster centers. It first ensures
      the descriptors are in a 2D NumPy array and checks that the number of descriptors is at least equal to the number of
        clusters. It then uses MiniBatchKMeans to fit the descriptors, with the number of clusters specified. After fitting, 
        the function returns the cluster centers, which form a dictionary of n_clusters clusters, each with the same 
        dimensionality as the original descriptors.
    """
    # ensure array and correct dtype
    descriptors = np.asarray(descriptors, dtype=np.float32)

    if descriptors.ndim != 2:
        raise ValueError("descriptors must be a 2D array of shape (N, D)")

    if descriptors.shape[0] < n_clusters:
        raise ValueError("Need at least n_clusters descriptors")

    # MiniBatchKMeans codebook (k = n_clusters)
    kmeans = MiniBatchKMeans(       # Use MiniBatchKMeans to compute cluster centers
        n_clusters=n_clusters,
        batch_size=10000,   
        random_state=42      
    )
    kmeans.fit(descriptors)     # Fit the descriptors

    # K x D matrix of cluster centers = dictionary D
    return kmeans.cluster_centers_      # Return the cluster centers


                                # **************************************************************

                                #                        VLAD Encoding & Normalization

                                #***************************************************************

def assignments(descriptors, clusters):
    """ 
    compute assignment matrix
    parameters:
        descriptors: TxD descriptor matrix
        clusters: KxD cluster matrix
    returns: TxK assignment matrix
    """
    """
    The function computes the assignment of descriptors to clusters. It uses a brute-force matcher (cv2.BFMatcher) 
    with L2 norm to find the nearest cluster center for each descriptor. For each descriptor, the function matches it to the 
    closest cluster and stores the result in a binary assignment matrix, where each row represents a descriptor and each column 
    represents a cluster. The matrix contains True at the position corresponding to the nearest cluster for each descriptor. 
    Finally, the assignment matrix is returned
    """

    # Function to assign each descriptor to the nearest cluster center
    bf = cv2.BFMatcher(cv2.NORM_L2) # Brute force matcher using L2 norm for matching descriptors to clusters
    matches = bf.knnMatch(descriptors, clusters, k=1) # Match descriptors to clusters
     # create hard assignment
    assignment = np.zeros((len(descriptors), len(clusters)), dtype=bool) # Initialize assignment matrix
    for i, match in enumerate(matches): # Iterate over all matches
        assignment[i, match[0].trainIdx] = True # Assign the descriptor to the nearest cluster center
    return assignment # Return the assignment matrix

def vlad(files, mus, powernorm, gmp=False, gamma=1000):
    """
    compute VLAD encoding for each files
    parameters: 
        files: list of N files containing each T local descriptors of dimension
        D
        mus: KxD matrix of cluster centers
        gmp: if set to True use generalized max pooling instead of sum pooling
    returns: NxK*D matrix of encodings
    """
    """
    The function iterates over each file in the files list. For each file, it loads the local descriptors (T descriptors of dimension D).
        If the file has no descriptors, it appends a zero vector to the encodings.
        It then computes the assignment of descriptors to cluster centers using the assignments function.
        For each cluster, the residuals (differences between the descriptors and the cluster center) are computed.
        If gmp is True, it applies Ridge regression to the residuals.
        If gmp is False, it sums the residuals (standard VLAD).
        The resulting vectors for each cluster are concatenated to form the VLAD encoding for the file.
        
        Normalization:
        If powernorm is True, it applies power normalization (signed square root) to the encoding.
        Finally, the encoding is L2 normalized.

        It returns a Nx(K*D) matrix, where N is the number of files, K is the number of clusters, and D is the dimension of each descriptor.
    """


# Get the number of clusters and dimension of cluster centers
    K = mus.shape[0]
    D = mus.shape[1]
    encodings = []  # Initialize the encodings

    for f in tqdm(files):   # Iterate over all files
        # load local descriptors for this image
        # with gzip.open(f, 'rb') as ff:      # Open the file
        #     desc = cPickle.load(ff, encoding='latin1')  # Load the descriptors shape: T x D
        desc = loadDescsFromFile(f)

        if desc is None or len(desc) == 0:
            # no descriptors -> zero vector
            f_enc = np.zeros((K * D), dtype=np.float32)
            encodings.append(f_enc)
            continue

        desc = np.asarray(desc, dtype=np.float32)# Compute the assignments and initialize
        T, D = desc.shape

        # association / assignment matrix or vector (depends on your implementation)
        a = assignments(desc, mus)

        f_enc = np.zeros((K * D), dtype=np.float32) # Initialize the VLAD encoding

        for k in range(K):
            # select descriptors assigned to cluster k
            if a.ndim == 2:
                # one-hot / association matrix: T x K
                idx = np.where(a[:, k] > 0)[0]
            else:
                # vector of cluster indices: length T
                idx = np.where(a == k)[0]

            if idx.size == 0:
                # no descriptors for this cluster -> keep zeros
                continue

            # residuals for this cluster: (T_k x D)
            R = desc[idx, :] - mus[k]

            if gmp:
                # ----- Generalized Max Pooling (bonus part f) -----
                # use Ridge regression: encoding is coef_ (1 x D)
                # handle tiny clusters robustly
                if R.shape[0] == 1:
                    # fallback: just take that residual
                    v_k = R[0]
                else:
                    ridge = Ridge(
                        alpha=gamma,
                        solver='sparse_cg',
                        fit_intercept=False,
                        max_iter=500
                    )
                    # target vector of ones
                    y = np.ones(R.shape[0], dtype=np.float32)
                    ridge.fit(R, y)
                    v_k = ridge.coef_.ravel().astype(np.float32)
            else:
                # ----- Standard VLAD: sum pooling -----
                v_k = R.sum(axis=0)

            # put this cluster's vector into the global VLAD vector
            f_enc[k * D:(k + 1) * D] = v_k

        # c) power normalization (signed sqrt) if requested
        if powernorm:
            p = 0.5  # exponent for power normalization
            f_enc = np.sign(f_enc) * (np.abs(f_enc) ** p)

        # final ℓ2 normalization
        norm = np.linalg.norm(f_enc)
        if norm > 0:
            f_enc = f_enc / norm

        encodings.append(f_enc.astype(np.float32))

    # Nx(K*D)
    return np.vstack(encodings)


   

def esvm(encs_test, encs_train, C=1000):
    """ 
    compute a new embedding using Exemplar Classification
    compute for each encs_test encoding an E-SVM using the
    encs_train as negatives   
    parameters: 
        encs_test: NxD matrix
        encs_train: MxD matrix

    returns: new encs_test matrix (NxD)
    """

    """
    The function first ensures that both encs_test and encs_train are NumPy arrays.
        It then creates a label vector y with the first entry as 1 (indicating a positive exemplar, i.e., the test encoding) and the rest as -1 (indicating the negatives, i.e., the training encodings).
        For each test encoding (indexed by i), it builds a training set where the test encoding is the positive sample (label 1) and the training encodings are the negative samples (label -1).
        A linear SVM classifier (LinearSVC) is trained on this set with a balanced class weight to handle the imbalance between positives and negatives, using the regularization parameter C=1000.
        The SVM's weight vector (coef_) is extracted, which represents the new embedding for the test encoding.
        The function applies this process in parallel to all test encodings using map (or optionally parmap if parallelism is set up).
        The new embeddings for all test encodings are collected and concatenated into a final matrix.
        The function returns a new NxD matrix, where N is the number of test samples and D is the dimensionality of the embeddings. Each row is the new embedding for a corresponding test sample.
    """


    # make sure we have numpy arrays
    encs_test = np.asarray(encs_test, dtype=np.float32)
    encs_train = np.asarray(encs_train, dtype=np.float32)

    N, D = encs_test.shape  # Get the number of test encodings and dimension
    M = encs_train.shape[0]     # Get the number of training encodings

    # set up labels: 1 positive (test sample), M negatives (all train)
    y = np.empty(M + 1, dtype=np.int32)
    y[0] = 1          # positive exemplar
    y[1:] = -1        # negatives

    def loop(i):
        # build training data for this exemplar SVM:
        # first row = current test vector (positive), rest = all train encodings (negatives)
        X = np.vstack((encs_test[i][None, :], encs_train))

        # train linear SVM with class_weight balanced, C=1000 as in the sheet
        clf = LinearSVC(C=C, class_weight='balanced', max_iter=10000)
        clf.fit(X, y)

        # weight vector is the new descriptor
        w = clf.coef_.ravel().astype(np.float32)

        # ℓ2-normalize the weight vector
        norm = np.linalg.norm(w)
        if norm > 0:
            w = w / norm

        # return as 1xD for concatenation later
        return w[None, :]

    # parallel map over all test encodings
    # new_encs = list(parmap(loop, tqdm(range(N))))
    new_encs = list(map(loop, tqdm(range(N))))
    new_encs = np.concatenate(new_encs, axis=0)

    # return new encodings (NxD)
    return new_encs


def distances(encs):
    """ 
    compute pairwise distances 

    parameters:
        encs:  TxK*D encoding matrix
    returns: TxT distance matrix
    """

    """
    The function first ensures that encs is a NumPy array with the correct data type (float32).
        It then L2-normalizes each encoding (row-wise) by dividing each encoding by its L2 norm. This ensures that each 
        encoding has unit length, which is necessary for cosine similarity.
        Cosine similarity between two vectors is computed as the dot product of their L2-normalized forms. This is done 
        using np.dot(encs_norm, encs_norm.T), which computes the pairwise similarity matrix.
        The function then computes the pairwise distances by subtracting the cosine similarity from 1.0, as cosine distance
        is defined as 1 - cosine similarity.
        The diagonal of the distance matrix (which represents the distance of each encoding to itself) is filled with the 
        maximum float value to ensure that it is ignored in further calculations.
        The function returns a TxT distance matrix, where each entry (i, j) represents the cosine distance between encoding i and encoding j.
    """
   

    # ensure numpy array
    encs = np.asarray(encs, dtype=np.float32)

    # l2-normalize each encoding (row-wise)
    norms = np.linalg.norm(encs, axis=1, keepdims=True)
    norms[norms == 0] = 1.0  # avoid division by zero
    encs_norm = encs / norms

    # cosine distance = 1 - cosine similarity
    # cosine similarity is just dot product of l2-normalized vectors
    sim = np.dot(encs_norm, encs_norm.T)
    dists = 1.0 - sim

    # mask out distance with itself (set diagonal to max float)
    np.fill_diagonal(dists, np.finfo(dists.dtype).max)

    return dists

def evaluate(encs, labels):
    """
    evaluate encodings assuming using associated labels
    parameters:
        encs: TxK*D encoding matrix
        labels: array/list of T labels
    """

    """
    The evaluate function computes top-1 accuracy and mean Average Precision (mAP) for a set of encodings. It calculates 
    pairwise distances between encodings, sorts them, and checks how well the closest neighbors match the true class labels. 
    It then prints the top-1 accuracy and mAP values.
    """
    dist_matrix = distances(encs)   # compute distance matrix
    # sort each row of the distance matrix
    indices = dist_matrix.argsort() # sort each row of the distance matrix

    n_encs = len(encs)  # get the number of encodings

    mAP = []        # initialize mean average precision
    correct = 0     # initialize correct count
    for r in range(n_encs):     # iterate over all rows
        precisions = []     # initialize list of precisions
        rel = 0     # initialize relevance count
        for k in range(n_encs-1):       # iterate over all columns
            if labels[ indices[r,k] ] == labels[ r ]:       # check if the labels match
                rel += 1                                    # increment relevance count
                precisions.append( rel / float(k+1) )          # compute precision
                if k == 0:                                  # check if the first column is correct
                    correct += 1                            # increment correct count
        avg_precision = np.mean(precisions)                 # compute average precision
        mAP.append(avg_precision)                           # append average precision
    mAP = np.mean(mAP)                                      # compute mean average precision

    print('Top-1 accuracy: {} - mAP: {}'.format(float(correct) / n_encs, mAP))  # print top-1 accuracy and mAP



# Additional Exercise
def computeDescs(filename):
    """
    Load image and compute SIFT descriptors at SIFT keypoints.
    Improvements:
      (1) set all keypoint angles to 0
      (2) Hellinger normalization: L1 normalize, then signed sqrt (NO L2 afterwards)
    Returns: Tx128 float32 array (may be empty)
    """
    img = cv2.imread(filename, cv2.IMREAD_GRAYSCALE)
    if img is None:
        raise FileNotFoundError(f"Could not read image: {filename}")

    sift = cv2.SIFT_create()

    kps = sift.detect(img, None)
    if not kps:
        return np.empty((0, 128), dtype=np.float32)

    # (1) set angles to 0
    for kp in kps:
        kp.angle = 0.0

    kps, desc = sift.compute(img, kps)
    if desc is None or len(desc) == 0:
        return np.empty((0, 128), dtype=np.float32)

    desc = desc.astype(np.float32)

    # (2) Hellinger: L1 then signed sqrt, no L2 afterwards
    l1 = np.sum(np.abs(desc), axis=1, keepdims=True)
    l1[l1 == 0] = 1.0
    desc = desc / l1
    desc = np.sign(desc) * np.sqrt(np.abs(desc))

    return desc

def loadDescsFromFile(path):
    if path.endswith(".pkl.gz"):
        with gzip.open(path, 'rb') as ff:
            return cPickle.load(ff, encoding='latin1')
    else:
        return computeDescs(path)
        

#Create multiple codebooks (5 runs of k-means)

def make_codebooks(files_train, n_codebooks=5, n_clusters=100,
                   max_desc=500000, overwrite=False, prefix='mus_cb'):
    """
    Train or load multiple codebooks. Returns list of KxD matrices.
    """
    codebooks = []
    for i in range(n_codebooks):
        fname = f'{prefix}{i}_K{n_clusters}.pkl.gz'
        if (not os.path.exists(fname)) or overwrite:
            print(f'[codebook {i+1}/{n_codebooks}] sampling descriptors...')
            # different seed/subset each time
            np.random.seed(100 + i)
            descs = loadRandomDescriptors(files_train, max_descriptors=max_desc)
            print(f'[codebook {i+1}] clustering...')
            # IMPORTANT: pass a different random_state
            kmeans = MiniBatchKMeans(
                n_clusters=n_clusters, batch_size=10000, random_state=100 + i
            )
            kmeans.fit(np.asarray(descs, dtype=np.float32))
            mus = kmeans.cluster_centers_.astype(np.float32)
            with gzip.open(fname, 'wb') as fOut:
                cPickle.dump(mus, fOut, -1)
        else:
            with gzip.open(fname, 'rb') as fIn:
                mus = cPickle.load(fIn)
        codebooks.append(mus)
    return codebooks

def multivlad(files, codebooks, powernorm=False, gmp=False, gamma=1.0):
    """
    Compute VLAD for each codebook and concatenate features.
    Returns: Nx(5*K*D)
    """
    enc_list = []
    for i, mus in enumerate(codebooks):
        print(f'  VLAD for codebook {i+1}/{len(codebooks)}')
        enc_i = vlad(files, mus, powernorm=powernorm, gmp=gmp, gamma=gamma)
        enc_list.append(enc_i)
    return np.concatenate(enc_list, axis=1).astype(np.float32)


def pca_whiten(train_X, test_X, out_dim=1000, subset=0):
    """
    Fit PCA(whiten=True) on train set (or subset), transform train and test.
    """
    train_X = np.asarray(train_X, dtype=np.float32)
    test_X  = np.asarray(test_X, dtype=np.float32)

    # choose subset for PCA fit (optional)
    fit_X = train_X
    if subset and subset < train_X.shape[0]:
        idx = np.random.choice(train_X.shape[0], subset, replace=False)
        fit_X = train_X[idx]

    # n_components must be <= min(n_samples, n_features)
    n_comp = min(out_dim, fit_X.shape[0], train_X.shape[1])

    pca = PCA(n_components=n_comp, whiten=True, svd_solver='randomized', random_state=42)
    pca.fit(fit_X)

    train_p = pca.transform(train_X).astype(np.float32)
    test_p  = pca.transform(test_X).astype(np.float32)

    # recommended for cosine distance
    train_p = normalize(train_p, norm='l2')
    test_p  = normalize(test_p, norm='l2')

    return train_p, test_p, pca

                                # **************************************************************

                                #                        Main Function 

                                #***************************************************************
"""
1. Initialize and parse arguments
2. Load file paths and labels
3. Load or compute the codebook
4. Compute VLAD encodings for the test set
5. Compute VLAD encodings for the training set
6. Save VLAD encodings
7. Evaluate test encodings
8. Compute Exemplar SVMs
9. Evaluate new encodings
10. Return
"""

if __name__ == '__main__':

    parser = argparse.ArgumentParser('retrieval')   # Initialize the argument parser
    parser = parseArgs(parser)  # Parse the arguments
    args = parser.parse_args()

    # load train/test file lists FIRST
    files_train, labels_train = getFiles(args.in_train, args.suffix_train, args.labels_train)
    files_test,  labels_test  = getFiles(args.in_test,  args.suffix_test,  args.labels_test)
    np.random.seed(42)  # fix random seed
    gamma = getattr(args, 'gamma', 1.0)


    if args.multivlad:
        codebooks = make_codebooks(
            files_train,
            n_codebooks=args.n_codebooks,
            n_clusters=args.n_clusters,
            max_desc=500000,
            overwrite=args.overwrite
        )

        # compute multi-vlad for test/train
        enc_test = multivlad(files_test, codebooks,
                            powernorm=args.powernorm,
                            gmp=args.gmp,
                            gamma=gamma)

        enc_train = multivlad(files_train, codebooks,
                            powernorm=args.powernorm,
                            gmp=args.gmp,
                            gamma=gamma)

        # PCA whitening to 1000 dims (fit on train)
        enc_train, enc_test, pca = pca_whiten(enc_train, enc_test,
                                            out_dim=args.pca_dim,
                                            subset=args.pca_subset)

        print("evaluate multi-VLAD + PCA-whiten")
        evaluate(enc_test, labels_test)

        print("evaluate multi-VLAD + PCA-whiten + E-SVM")
        enc_test_esvm = esvm(enc_test, enc_train, C=args.C)
        evaluate(enc_test_esvm, labels_test)

    else:

        # parser = argparse.ArgumentParser('retrieval')   # Initialize the argument parser
        # parser = parseArgs(parser)  # Parse the arguments
        # args = parser.parse_args()
        # np.random.seed(42)  # fix random seed

        # gamma = getattr(args, 'gamma', 1.0)

        # # a) dictionary
        # files_train, labels_train = getFiles(args.in_train, args.suffix_train,        # Load training files and labels
        #                                     args.labels_train)
        # print('#train: {}'.format(len(files_train)))        # Print the number of training files loaded  

        if not os.path.exists('mus.pkl.gz'):            # Check if the codebook exists
        
            print(' load random descriptors for dictionary')
            descriptors = loadRandomDescriptors(files_train, max_descriptors=500000)    # Load random descriptors
            
            print(' loaded {} descriptors:'.format(len(descriptors)))
            print("Generating codebook...") # Generate codebook
            # cluster centers (codebook) with MiniBatchKMeans, k = 100
            print(' compute dictionary')
            mus = dictionary(descriptors, 100)  # Compute the codebook
                                                                            # save the codebook
            with gzip.open('mus.pkl.gz', 'wb') as fOut:
                cPickle.dump(mus, fOut, -1)
                print("Codebook generated and saved.") # Print codebook generated and saved
        else:
            with gzip.open('mus.pkl.gz', 'rb') as f:
                mus = cPickle.load(f)
            
            print("Codebook loaded from disk.")     # Print codebook loaded from disk

        # b/c) VLAD encoding (+ optional power norm / GMP) for test set
        print(' compute VLAD for test')
        files_test, labels_test = getFiles(args.in_test, args.suffix_test,
                                        args.labels_test)
        print("VLAD encodings computed.") # VLAD encodings computed
        print('#test: {}'.format(len(files_test)))
    
        # Compute VLAD encodings for the test set
        print("Computing VLAD encodings for test data...") # Compute VLAD encodings for the test set
    
        fname = 'enc_test_gmp{}.pkl.gz'.format(gamma) if args.gmp else 'enc_test.pkl.gz'
        if not os.path.exists(fname) or args.overwrite:
            enc_test = vlad(files_test, mus,
                            powernorm=args.powernorm,
                            gmp=args.gmp,
                            gamma=gamma)
            with gzip.open(fname, 'wb') as fOut:
                cPickle.dump(enc_test, fOut, -1)
        else:
            with gzip.open(fname, 'rb') as f:
                enc_test = cPickle.load(f)
        print("VLAD encodings for test computed") # VLAD encodings for training computed

        # cross-evaluate test encodings (plain VLAD + normalization)
        print(' evaluate')
        evaluate(enc_test, labels_test)
        
        # d) compute exemplar SVMs
        # Compute VLAD encodings for the training set
        print("Computing VLAD encodings for training data...") # Compute VLAD encodings for the training set
        fname = 'enc_train_gmp{}.pkl.gz'.format(gamma) if args.gmp else 'enc_train.pkl.gz'
        if not os.path.exists(fname) or args.overwrite:
            enc_train = vlad(files_train, mus,
                            powernorm=args.powernorm,
                            gmp=args.gmp,
                            gamma=gamma)
            with gzip.open(fname, 'wb') as fOut:
                cPickle.dump(enc_train, fOut, -1)
        else:
            with gzip.open(fname, 'rb') as f:
                enc_train = cPickle.load(f)

                
        print("VLAD encodings for training computed.") # VLAD encodings for training computed
        print(' esvm computation')
        # compute new test embeddings via exemplar SVMs
        # enc_test = esvm(enc_test, enc_train)
        enc_test = esvm(enc_test, enc_train, C=args.C)

        # eval E-SVM embeddings
        print(" Evaluate new encodings after Exemplar SVMs")                 # Evaluate new encodings
        evaluate(enc_test, labels_test)
